/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#34302c",
        "surface-bright": "#fff8f5",
        "secondary-container": "#fed488",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdea5",
        tertiary: "#272725",
        "on-tertiary-fixed": "#1b1c1a",
        "on-surface-variant": "#584141",
        "primary-fixed": "#ffdada",
        "on-primary": "#ffffff",
        "on-primary-container": "#ff828a",
        "surface-dim": "#e1d8d4",
        "tertiary-container": "#3d3d3b",
        "surface-container-high": "#efe6e2",
        "primary-fixed-dim": "#ffb3b5",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb3b5",
        "on-tertiary-container": "#a9a8a4",
        secondary: "#775a19",
        "surface-tint": "#af2b3e",
        "on-background": "#1e1b18",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#40000b",
        "outline-variant": "#e0bfbf",
        "on-surface": "#1e1b18",
        "on-primary-fixed-variant": "#8e0f28",
        "surface-container": "#f5ece7",
        "on-secondary-fixed": "#261900",
        "error-container": "#ffdad6",
        "surface-variant": "#e9e1dc",
        "inverse-on-surface": "#f8efea",
        surface: "#fff8f5",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary-container": "#785a1a",
        "surface-container-low": "#fbf2ed",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#474744",
        "on-secondary-fixed-variant": "#5d4201",
        "primary-container": "#800020",
        "tertiary-fixed-dim": "#c8c6c3",
        "tertiary-fixed": "#e4e2de",
        background: "#fff8f5",
        "on-tertiary": "#ffffff",
        primary: "#570013",
        outline: "#8c7071",
        "surface-container-highest": "#e9e1dc",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        lg: "48px",
        xs: "4px",
        "margin-mobile": "16px",
        gutter: "24px",
        "container-max": "1280px",
        xl: "80px",
        sm: "12px",
        base: "8px",
        md: "24px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "body-md": ["Libre Franklin", "sans-serif"],
        caption: ["Libre Franklin", "sans-serif"],
        "body-lg": ["Libre Franklin", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-xl": ["Playfair Display", "serif"],
        "label-md": ["Libre Franklin", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};

